public void testGetProcedures() throws Exception {
    try {
        lDAO.getProcedures("2");
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}