public void testGetHospitalException() throws Exception {
    try {
        evilDAO.getHospital("");
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}