public void testRemoveHospitalAssignmentException() throws Exception {
    try {
        evilDAO.removeHospitalAssignment(0L, "");
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}