public void testCheckPatientExistsException() throws Exception {
    try {
        evilDAO.checkPatientExists(0L);
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}