public void testGetOfficeVisitsWithInstructions() throws Exception {
    try {
        evilDAO.getOfficeVisitsWithInstructions(1);
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}