public void testAddReferral() {
    ReferralBean bean = new ReferralBean();
    try {
        dao.addReferral(bean);
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}