public void testGetReferralsFromOV() {
    try {
        dao.getReferralsFromOV(1L);
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}