public void testRemovePatientFromListBad() throws Exception {
    try {
        EvilrmDAO.removePatientFromList(1, 2);
        fail();
    } catch (DBException e) {
        assertSame(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}