public void testUpdateCodeException() throws Exception {
    try {
        evilDAO.updateCode(new MedicationBean());
        fail("DBException should have been thrown");
    } catch (DBException e) {
        assertEquals(EvilDAOFactory.MESSAGE, e.getSQLException().getMessage());
    }
}