public void testNoMatch() throws Exception {
    qa.setAnswer("12345678");
    qa.setConfirmAnswer("123456789");
    qa.setQuestion("12345678");
    try {
        qav.validate(qa);
        fail("exception should have been thrown");
    } catch (FormValidationException e) {
        assertEquals(1, e.getErrorList().size());
        assertEquals("Security answers do not match", e.getErrorList().get(0));
    }
}